### ISSUE TITLE
Help with Deployment

### ISSUE THREAD

**Issue by safwansamsudeen** [cedrictailly/sveltekit-io#1]
Hey,

Thanks for the great library!

I've been struggling for a couple weeks with deploying my application based on SvelteKit IO. As, two ports are started up, I'm not sure how both can be accessed online. I have no idea how to deploy two ports at the same time. Could you help me out?

**Comment by cedrictailly** [comment]
Thank you for your feedback, it all depends on the DevOps part, tell me more about your hosting?

**Comment by safwansamsudeen** [comment]
I'm trying to deploy it on Render or Vercel - but I really don't know, and that's why I'm asking how you would do it. Thanks!

**Comment by cedrictailly** [comment]
Apparently it is not possible to open different ports on Vercel, but I don't really know this platform, I generally use VPS for my deployments.

It seems that there is a vercel.json or server.json file which is taken into account but a priori no notion of reverse proxy, so it will be complicated or impossible with Vercel.
